### ISSUE TITLE
Caching of a route should be decided inside of the callback.

### ISSUE THREAD

**Issue by wolfgangschoeffel** [em4nl/unplug#6]
At the moment a route with an optional first parameter acts like a catchall route and the .htaccess gets filled with crap.

    e.g. $router->get('/:project', function ($req) {

        // find project
       // if project is not found do not cache the path
    });

There should be a way to disable caching if the corresponding :project is not found.

**Comment by smotchkkiss** [comment]
Caching can now be disabled by explicitly passing `false` as the second parameter to `ok()`, `not_found()`, `moved_permanently()` and `found()`. Also, for `not_found`, `false` is the default.
